import type { ResourceConfig } from "@/types/admin";

const habilitadoOptions = [
  { label: "Ativo", value: "S" },
  { label: "Inativo", value: "N" },
];

const bannerTipoOptions = [
  { label: "Home mega", value: "home_mega" },
  { label: "Home grande", value: "home_grande" },
  { label: "Banner medio", value: "banner_medio" },
  { label: "Mega banner", value: "mega_banner" },
];

export const resources: Record<string, ResourceConfig> = {
  produtos: {
    title: "Produtos",
    description: "Gerencie catalogo, codigos, status comerciais e metadados dos produtos.",
    endpoint: "/api/v1/produtos",
    idField: "id_produto",
    searchPlaceholder: "Buscar por produto, codigo ou descricao",
    columns: [
      { name: "id_produto", label: "ID" },
      { name: "codigo", label: "Codigo" },
      { name: "produto", label: "Produto" },
      { name: "habilitado", label: "Status" },
      { name: "site", label: "Site" },
      { name: "promocao", label: "Promocao" },
    ],
    formFields: [
      { name: "id_tipo_produto", label: "Tipo", type: "number", required: true },
      { name: "produto", label: "Produto", required: true },
      { name: "codigo", label: "Codigo", required: true },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "imagem", label: "Imagem" },
      { name: "site", label: "Site", type: "select", options: habilitadoOptions },
      { name: "promocao", label: "Promocao", type: "select", options: habilitadoOptions },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { id_tipo_produto: 1, site: "N", promocao: "N", habilitado: "S" },
    imageManager: true,
  },
  categorias: {
    title: "Categorias",
    description: "Organize as categorias comerciais usadas no site e no catalogo.",
    endpoint: "/api/v1/categorias",
    idField: "id_categoria",
    searchPlaceholder: "Buscar categorias",
    columns: [
      { name: "id_categoria", label: "ID" },
      { name: "categoria", label: "Categoria" },
      { name: "descricao", label: "Descricao" },
      { name: "habilitado", label: "Status" },
    ],
    formFields: [
      { name: "id_categoria", label: "ID", type: "number" },
      { name: "categoria", label: "Categoria", required: true },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "icon", label: "Icone" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { habilitado: "S" },
  },
  subcategorias: {
    title: "Subcategorias",
    description: "Gerencie as subdivisoes das categorias e sua ordenacao.",
    endpoint: "/api/v1/subcategorias",
    idField: "id_subcategoria",
    searchPlaceholder: "Buscar subcategorias",
    columns: [
      { name: "id_subcategoria", label: "ID" },
      { name: "id_categoria", label: "Categoria" },
      { name: "subcategoria", label: "Subcategoria" },
      { name: "ordem", label: "Ordem" },
      { name: "habilitado", label: "Status" },
    ],
    formFields: [
      { name: "id_categoria", label: "ID categoria", type: "number", required: true },
      { name: "id_subcategoria", label: "ID", type: "number" },
      { name: "subcategoria", label: "Subcategoria", required: true },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "ordem", label: "Ordem", type: "number" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { ordem: 0, habilitado: "S" },
  },
  "publicos-alvos": {
    title: "Publicos-alvo",
    description: "Segmentos de compra usados para recomendar produtos.",
    endpoint: "/api/v1/publicos-alvos",
    idField: "id_publico_alvo",
    searchPlaceholder: "Buscar publicos-alvo",
    columns: [
      { name: "id_publico_alvo", label: "ID" },
      { name: "publico_alvo", label: "Publico" },
      { name: "descricao", label: "Descricao" },
      { name: "ordem", label: "Ordem" },
      { name: "habilitado", label: "Status" },
    ],
    formFields: [
      { name: "id_publico_alvo", label: "ID", type: "number" },
      { name: "publico_alvo", label: "Publico-alvo", required: true },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "ordem", label: "Ordem", type: "number" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { ordem: 0, habilitado: "S" },
  },
  "datas-promocionais": {
    title: "Datas promocionais",
    description: "Datas sazonais e campanhas para destacar produtos.",
    endpoint: "/api/v1/datas-promocionais",
    idField: "id_data_promocional",
    searchPlaceholder: "Buscar datas promocionais",
    columns: [
      { name: "id_data_promocional", label: "ID" },
      { name: "data_promocional", label: "Data promocional" },
      { name: "data", label: "Data" },
      { name: "ordem", label: "Ordem" },
      { name: "habilitado", label: "Status" },
    ],
    formFields: [
      { name: "id_data_promocional", label: "ID", type: "number" },
      { name: "data_promocional", label: "Nome", required: true },
      { name: "data", label: "Data" },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "ordem", label: "Ordem", type: "number" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { ordem: 0, habilitado: "S" },
  },
  banners: {
    title: "Banners",
    description: "Gerencie campanhas, links, periodo de exibicao e status dos banners do site.",
    endpoint: "/api/v1/banners",
    idField: "id_banner",
    searchPlaceholder: "Buscar por titulo, URL ou imagem",
    columns: [
      { name: "id_banner", label: "ID" },
      { name: "tipo", label: "Tipo" },
      { name: "titulo", label: "Titulo" },
      { name: "ordem", label: "Ordem" },
      { name: "habilitado", label: "Status" },
      { name: "url_banner", label: "Imagem" },
    ],
    formFields: [
      { name: "id_banner", label: "ID", type: "number" },
      { name: "tipo", label: "Tipo", type: "select", options: bannerTipoOptions, required: true },
      { name: "titulo", label: "Titulo" },
      { name: "url", label: "URL destino" },
      { name: "id_tipo_produto", label: "ID tipo produto", type: "number" },
      { name: "data_inicial", label: "Data inicial", type: "date" },
      { name: "data_final", label: "Data final", type: "date" },
      { name: "ordem", label: "Ordem", type: "number" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
      { name: "cliques", label: "Cliques", type: "number" },
      { name: "url_banner", label: "URL da imagem" },
    ],
    defaultValues: {
      tipo: "home_grande",
      id_tipo_produto: 0,
      ordem: 0,
      habilitado: "S",
      data_inicial: new Date().toISOString().slice(0, 10),
      data_final: "2030-12-31",
    },
  },
  clientes: {
    title: "Clientes",
    description: "Cadastre empresas, contatos comerciais e dados fiscais.",
    endpoint: "/api/v1/clientes",
    idField: "id_cliente",
    searchPlaceholder: "Buscar por fantasia, razao social, documento ou email",
    columns: [
      { name: "id_cliente", label: "ID" },
      { name: "fantasia", label: "Fantasia" },
      { name: "cnpj_cpf", label: "Documento" },
      { name: "cidade", label: "Cidade" },
      { name: "email", label: "Email" },
      { name: "habilitado", label: "Status" },
    ],
    formFields: [
      { name: "id_cliente", label: "ID", type: "number" },
      { name: "pessoa", label: "Pessoa", type: "select", options: [{ label: "Juridica", value: "J" }, { label: "Fisica", value: "F" }] },
      { name: "fantasia", label: "Fantasia", required: true },
      { name: "razao_social", label: "Razao social" },
      { name: "cnpj_cpf", label: "CNPJ/CPF" },
      { name: "email", label: "Email", type: "email" },
      { name: "tel", label: "Telefone" },
      { name: "cidade", label: "Cidade" },
      { name: "uf", label: "UF" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { pessoa: "J", pais: "BRASIL", habilitado: "S" },
  },
  usuarios: {
    title: "Usuarios",
    description: "Equipe interna com acesso administrativo.",
    endpoint: "/api/v1/usuarios",
    idField: "id_usuario",
    searchPlaceholder: "Buscar usuarios",
    columns: [
      { name: "id_usuario", label: "ID" },
      { name: "usuario", label: "Usuario" },
      { name: "nome", label: "Nome" },
      { name: "email", label: "Email" },
      { name: "habilitado", label: "Status" },
    ],
    formFields: [
      { name: "usuario", label: "Usuario", required: true },
      { name: "nome", label: "Nome", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "senha", label: "Senha", required: true },
      { name: "cidade", label: "Cidade" },
      { name: "uf", label: "UF" },
      { name: "habilitado", label: "Status", type: "select", options: habilitadoOptions },
    ],
    defaultValues: { habilitado: "S" },
  },
  orcamentos: {
    title: "Orçamentos",
    description: "Acompanhe propostas, contatos e histórico comercial.",
    endpoint: "/api/v1/orcamentos",
    idField: "id_orcamento",
    searchPlaceholder: "Buscar orçamentos",
    columns: [
      { name: "id_orcamento", label: "ID" },
      { name: "data_orcamento", label: "Data" },
      { name: "fantasia", label: "Cliente" },
      { name: "contato", label: "Contato" },
      { name: "email", label: "Email" },
      { name: "cidade", label: "Cidade" },
    ],
    formFields: [
      { name: "data_orcamento", label: "Data", type: "date", required: true },
      { name: "fantasia", label: "Fantasia" },
      { name: "contato", label: "Contato", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "tel", label: "Telefone" },
      { name: "endereco", label: "Endereco", required: true },
      { name: "cidade", label: "Cidade" },
      { name: "uf", label: "UF" },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
    defaultValues: { data_orcamento: new Date().toISOString().slice(0, 10) },
  },
};
